const products = [
  // ELECTRONICS
  {
    id: 1,
    category: "Electronics",
    name: "Wireless Earbuds Pro",
    price: 700,
    icon: "fa-headphones",
    rating: 4.6,
    reviews: 128,
    tag: "NEW",
    description: "سماعات لاسلكية بجودة صوت عالية وبطارية تدوم طويلاً.",
    details: "اتصال بلوتوث 5.3، مقاومة للماء، صوت نقي وباس قوي.",
  },
  {
    id: 2,
    category: "Electronics",
    name: "Smart Watch X1",
    price: 1500,
    icon: "fa-clock",
    rating: 4.4,
    reviews: 96,
    description: "ساعة ذكية لتتبع اللياقة والإشعارات اليومية.",
    details: "شاشة AMOLED، تتبع معدل ضربات القلب، بطارية 7 أيام.",
  },
  {
    id: 3,
    category: "Electronics",
    name: "Portable Speaker",
    price: 600,
    icon: "fa-volume-high",
    rating: 4.2,
    reviews: 64,
    tag: "SALE",
    description: "سماعة بلوتوث محمولة بصوت قوي ومقاومة للماء.",
    details: "تشغيل حتى 12 ساعة، مقاومة للماء IPX6.",
  },

  // FASHION
  {
    id: 4,
    category: "Fashion",
    name: "Classic Black T-Shirt",
    price: 400,
    icon: "fa-shirt",
    rating: 4.5,
    reviews: 210,
    description: "تيشيرت أسود بتصميم عصري وخامة مريحة مناسبة للاستخدام اليومي.",
    details: "خامة قطنية ناعمة، تصميم مريح، مناسب للارتداء اليومي.",
  },
  {
    id: 5,
    category: "Fashion",
    name: "Oversized Hoodie",
    price: 600,
    icon: "fa-shirt",
    rating: 4.7,
    reviews: 150,
    tag: "NEW",
    description: "هودي واسع بتصميم عصري يمنحك الراحة والأناقة.",
    details: "خامة دافئة، تصميم Oversized، مناسب للخروج والاستخدام اليومي.",
  },
  {
    id: 6,
    category: "Fashion",
    name: "Premium Jacket",
    price: 1300,
    icon: "fa-vest",
    rating: 4.3,
    reviews: 88,
    description: "جاكت أنيق بتصميم Premium يناسب الإطلالات المختلفة.",
    details: "خامة عالية الجودة، تصميم عصري، مناسب لفصل الشتاء.",
  },

  // HOME & LIVING
  {
    id: 7,
    category: "Home & Living",
    name: "Aroma Diffuser",
    price: 350,
    icon: "fa-fan",
    rating: 4.4,
    reviews: 73,
    description: "جهاز ترطيب ونشر روائح لغرفتك.",
    details: "سعة 300 مل، إضاءة ليلية هادئة.",
  },
  {
    id: 8,
    category: "Home & Living",
    name: "Cozy Throw Blanket",
    price: 270,
    icon: "fa-couch",
    rating: 4.6,
    reviews: 59,
    tag: "SALE",
    description: "بطانية ناعمة ودافئة لمنزلك.",
    details: "خامة فليس فاخرة، مقاسات متعددة.",
  },

  // SPORTS
  {
    id: 9,
    category: "Sports",
    name: "Training T-Shirt",
    price: 400,
    icon: "fa-dumbbell",
    rating: 4.3,
    reviews: 102,
    description: "تيشيرت رياضي خفيف ومريح للتمارين والأنشطة الرياضية.",
    details: "خامة خفيفة وسريعة الجفاف، حرية حركة ممتازة.",
  },
  {
    id: 10,
    category: "Sports",
    name: "Gym Shorts",
    price: 430,
    icon: "fa-person-running",
    rating: 4.2,
    reviews: 77,
    description: "شورت رياضي مريح مناسب للجيم والتمارين اليومية.",
    details: "تصميم مرن، خامة مريحة، مناسب للتمارين المختلفة.",
  },
  {
    id: 11,
    category: "Sports",
    name: "Sports Tracksuit",
    price: 720,
    icon: "fa-shirt",
    rating: 4.5,
    reviews: 64,
    tag: "NEW",
    description: "تريننج رياضي كامل بتصميم أنيق ومريح.",
    details: "خامة مريحة، تصميم رياضي عصري، مناسب للتدريب والخروج.",
  },

  // BEAUTY
  {
    id: 12,
    category: "Beauty",
    name: "Hydrating Face Serum",
    price: 380,
    icon: "fa-spa",
    rating: 4.7,
    reviews: 140,
    description: "سيروم مرطب للبشرة بمكونات طبيعية.",
    details: "يحتوي على حمض الهيالورونيك، مناسب لكل أنواع البشرة.",
  },
  {
    id: 13,
    category: "Beauty",
    name: "Matte Lipstick Set",
    price: 550,
    icon: "fa-heart",
    rating: 4.5,
    reviews: 98,
    tag: "SALE",
    description: "مجموعة أحمر شفاه مطفي بألوان متعددة.",
    details: "تركيبة طويلة الثبات وخفيفة على الشفاه.",
  },

  // GROCERIES
  {
    id: 14,
    category: "Groceries",
    name: "Organic Coffee Beans",
    price: 820,
    icon: "fa-mug-hot",
    rating: 4.6,
    reviews: 112,
    description: "حبوب قهوة عضوية محمصة طازة.",
    details: "وزن 250 جم، تحميص متوسط.",
  },
  {
    id: 15,
    category: "Groceries",
    name: "Mixed Nuts Pack",
    price: 370,
    icon: "fa-seedling",
    rating: 4.4,
    reviews: 80,
    description: "مكسرات مشكلة صحية ومغذية.",
    details: "وزن 500 جم، بدون إضافات.",
  },

  // ACCESSORIES
  {
    id: 16,
    category: "Accessories",
    name: "Classic Watch",
    price: 420,
    icon: "fa-clock",
    rating: 4.5,
    reviews: 70,
    description: "ساعة بتصميم كلاسيكي أنيق تناسب مختلف الإطلالات.",
    details: "تصميم أنيق، مناسبة للاستخدام اليومي والمناسبات.",
  },
  {
    id: 17,
    category: "Accessories",
    name: "Premium Sunglasses",
    price: 290,
    icon: "fa-glasses",
    rating: 4.3,
    reviews: 55,
    tag: "SALE",
    description: "نظارة شمسية بتصميم عصري تضيف لمسة مميزة لإطلالتك.",
    details: "تصميم خفيف ومريح للاستخدام اليومي.",
  },
];
